# This file configures the analyzer for Dart code
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "lib/core/gen/**"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # Disable rules that are too strict for this project
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    
    # Keep these useful rules
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
