name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Root-level linting and quality checks
  root-lint:
    name: Root Level Linting
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, '.eslintrc.js') || contains(github.event.head_commit.modified, '.prettierrc') || contains(github.event.head_commit.modified, 'tsconfig.json')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Run root-level linting
        uses: ./.github/workflows/lint-and-quality.yml
        with:
          working-directory: '.'
          node-version: '18'
          pnpm-version: '8'

  # Individual application workflows
  convex-ci:
    name: Convex Backend CI
    uses: ./.github/workflows/convex-ci.yml
    if: contains(github.event.head_commit.modified, 'Convex/') || github.event_name == 'push'

  web-ci:
    name: Web Application CI
    uses: ./.github/workflows/web-ci.yml
    if: contains(github.event.head_commit.modified, 'Web/') || github.event_name == 'push'

  react-native-ci:
    name: React Native Application CI
    uses: ./.github/workflows/react-native-ci.yml
    if: contains(github.event.head_commit.modified, 'ReactNative/') || github.event_name == 'push'

  # Dependency and security checks
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level=moderate

      - name: Check for vulnerable dependencies
        run: |
          if pnpm audit --audit-level=high; then
            echo "No high-severity vulnerabilities found"
          else
            echo "High-severity vulnerabilities detected"
            exit 1
          fi

  # Final status check
  ci-status:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [root-lint, convex-ci, web-ci, react-native-ci, security-audit]
    if: always()

    steps:
      - name: Check all CI jobs status
        run: |
          if [ "${{ needs.root-lint.result }}" = "failure" ] || \
             [ "${{ needs.convex-ci.result }}" = "failure" ] || \
             [ "${{ needs.web-ci.result }}" = "failure" ] || \
             [ "${{ needs.react-native-ci.result }}" = "failure" ] || \
             [ "${{ needs.security-audit.result }}" = "failure" ]; then
            echo "Some CI jobs failed"
            exit 1
          else
            echo "All CI jobs passed successfully"
          fi

      - name: Create CI status summary
        run: |
          echo "## CI/CD Pipeline Status" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Component | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Root Linting | ${{ needs.root-lint.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Convex Backend | ${{ needs.convex-ci.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Web Application | ${{ needs.web-ci.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| React Native App | ${{ needs.react-native-ci.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security Audit | ${{ needs.security-audit.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pipeline completed at $(date)" >> $GITHUB_STEP_SUMMARY

  # Deployment coordination (only on main branch)
  deploy-coordination:
    name: Deployment Coordination
    runs-on: ubuntu-latest
    needs: ci-status
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.ci-status.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment Summary
        run: |
          echo "## 🚀 Production Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ All CI checks passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Code quality verified" >> $GITHUB_STEP_SUMMARY
          echo "✅ Security audit completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Status:" >> $GITHUB_STEP_SUMMARY
          echo "- **Web Application**: Deployed to Vercel" >> $GITHUB_STEP_SUMMARY
          echo "- **React Native**: Published to Expo" >> $GITHUB_STEP_SUMMARY
          echo "- **Convex Backend**: Deployed to Convex" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 **Live URLs:**" >> $GITHUB_STEP_SUMMARY
          echo "- Web: [Production URL](https://echoinwhispr.vercel.app)" >> $GITHUB_STEP_SUMMARY
          echo "- Mobile: Available via Expo Go" >> $GITHUB_STEP_SUMMARY